
[ClassVersion("1.0.0.0"), FriendlyName("cPrinter")]
class cPrinter : OMI_BaseResource
{
	[Key, Description("The name of the printer")] String Name;
	[Write, ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
	[Write, ValueMap{"TCPIP","Papercut","LPR"}, Values{"TCPIP","Papercut","LPR"}] String PortType;
	[Required, Description("The name of the printer port")] String PortName;
	[Required, Description("The fqdn of the printer")] String Address;
	[Required, Description("The name of the driver")] String DriverName;
	[Write, Description("The LPR queue name")] String LprQueue;
	[Write, Description("Sets the printer shared status")] Boolean Shared;
	[Write, Description("Sets if the printer should enable SNMP")] Boolean SNMPEnabled;
	[Write, Description("Sets the SNMP Community name")] String SNMPCommunityName;
	[Write, Description("Sets the SNMP index")] Sint16 SNMPIndex;
	[Write, Description("Sets the printer permissions")] String PermissionSDDL;
};

